{"uid":"863e9e31b0aa2da6","name":"An uncaught error was detected outside of a test","fullName":".An uncaught error was detected outside of a test","historyId":"52a12849550d3513996e41b83e83be38","time":{"start":1672265865063,"stop":1672265874062,"duration":8999},"description":"","descriptionHtml":"","status":"broken","statusMessage":"The following error originated from your test code, not from Cypress.\n                \n                  > Cannot convert undefined or null to object\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n                \n                  > Cannot convert undefined or null to object\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.\n                    at Function.values (<anonymous>)\n                    at Suite.eval (webpack:///./cypress/e2e/testcases/Services.cy.js:102:11)\n                    at ./cypress/e2e/testcases/Services.cy.js (webpack:///./cypress/e2e/testcases/Services.cy.js:101:0)\n                    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n                    at 0 (https://qa.appiskey.com/__cypress/tests?p=cypress\\e2e\\testcases\\Services.cy.js:312:18)\n                    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n                    at eval (webpack:///webpack/bootstrap:83:0)\n                    at eval (https://qa.appiskey.com/__cypress/tests?p=cypress\\e2e\\testcases\\Services.cy.js:87:10)\n                    at eval (<anonymous>)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"suite","value":""},{"name":"testClass","value":""},{"name":"testMethod","value":"An uncaught error was detected outside of a test"},{"name":"package","value":""},{"name":"resultFormat","value":"allure1"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"c80c5ad37fca67c5","status":"broken","statusDetails":"The following error originated from your test code, not from Cypress.\n                \n                  > Cannot convert undefined or null to object\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.","time":{"start":1672265865063,"stop":1672265874062,"duration":8999}}]},"tags":[]},"source":"863e9e31b0aa2da6.json","parameterValues":[]}